[package]
name = "dartfrog_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
anyhow = "1.0"
hyperware_process_lib = { version = "1.0.3", features = ["logging"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
